version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - wasure-sql
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      PYTHONPATH: "/"

  wasure-sql:
      image: postgres:15
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      volumes:
        - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: